# Home Assistant configuration.yaml

################
# command_line #
################
command_line:
  - switch:
      name: fan_on
      unique_id: fan_on
# ssh is only required if HA and rpitx run on different machines
      command_on: "ssh -i /config/id_rsa -o StrictHostKeyChecking=no -q pi@<YOUR.PI.IP.ADDRESS> sudo ./rpitx/sendiq -s 250000 -f 868.0000e6 -t u8 -i ./rpitx/fan-all-on.iq"
      command_off: off
# HA doesn't get feedback if the device is on or off.  This returns the switch always back to the off-state.  
     command_state: off

################
# emulated_hue #
################
emulated_hue:
  listen_port: 80
  expose_by_default: false
  entities:
    switch.fan_on:
      name: "fan on"
      hidden: false

##############
# automation #
##############
automation:
  - alias: webhook_fan_on
    trigger:
    - platform: webhook
      webhook_id: <PICK-A-RANDOM-WEBHOOK-ID>
    condition: []
    action:
    - data: {}
      entity_id: switch.fan_on
      service: switch.turn_on
    mode: single
